### ISSUE TITLE
1.19.1 support

### ISSUE THREAD

**Issue by Romvnly-Gaming** [ZtereoHYPE/AutoTechno#2]
i think this mod needs required version update cuz no work on 1.19.1

many us tanks, 

romvnly

**Comment by DragonEggBedrockBreaking** [comment]
Ah, there seems to be a version lock. I will try and sort it out tomorrow.

**Comment by DragonEggBedrockBreaking** [comment]
Done. https://modrinth.com/mod/autotechno/version/0.2.1
