### ISSUE TITLE
1.20.1

### ISSUE THREAD

**Issue by lowercasebtw** [ZtereoHYPE/AutoTechno#3]
Please update to 1.20 and switch to Quilt, and remove Fabric

**Comment by DragonEggBedrockBreaking** [comment]
There is no good reason for us to switch to Quilt, as Quilt should be able to run all fabric mods. If it cannot run this one, please file a separate report. We will update the mod to 1.20.x soon(TM).

**Comment by DragonEggBedrockBreaking** [comment]
see 0.2.3
